### ISSUE TITLE
New meta-box on New Post view for posts and custom post types

### ISSUE THREAD

**Issue by RyanBayne** [RyanBayne/TwitchPress#111]
thatgirlslays said...

> Just to be clear on this, I am not looking for any integration with posting Twitch Press content to social media such as Twitter/Facebook. What I'm referring to is how NextScripts' plugin, when posting certain post types, provides a check box on the Add/Edit post page. If the box is checked, then their plugin posts to whatever social media accounts you previously set up.

> What I'd be interested in for Twitch Press, is when someone creates a post (or other custom post type), they have the option to check a box that will then share that post on their Twitch channel feed.

> She requires a meta-box with checkbox to indicate that the post is to be shared on a Twitch feed. The meta-box will probably fill up with various options so consider other issues that could be complete when doing this work.

**Comment by ThatGirlSlays** [comment]
Yes this is exactly what I want, and it probably would have been simpler to not compare it to or mention Next Scripts plugin haha! A simple meta box, exactly.

**Comment by RyanBayne** [comment]
Well we're figuring it all out and you're clever enough to follow me and I'm following you. This is what a new project needs.

I notice you are watching the entire project and you're the first to star it (excellent). You might find it sends you too many email notifications being a follower though.

**It is possible to subscribe to individual issues instead.**

**Comment by ThatGirlSlays** [comment]
I am aware. And I might switch to individual projects if I feel the notifications are too much. Thanks!

**Comment by RyanBayne** [comment]
![image](https://user-images.githubusercontent.com/25900125/29254325-2c0d46a4-808b-11e7-8e8c-ad353b97c0db.png)

A post box for controlling the sharing of content has been added. 

Settings have also been added to control the post box display on different post type.
