### ISSUE TITLE
Investigate 401 scenario

### ISSUE THREAD

**Issue by RyanBayne** [RyanBayne/TwitchPress#170]
User us getting an access token and 1 minute later they get a 401 and no token returned. 

Status in the Help tab was fine and then suddenly not.

**Comment by RyanBayne** [comment]
The nature of the 401 error code means that it is difficult to debug without complete control over a users WordPress - downtime! There could be multiple causes basically. 

So my focus has been to improve the information we see in the Help tab and I'm working on improving the log entries that are happening around the time we see the problem arise. 

![image](https://user-images.githubusercontent.com/25900125/32921199-86a6903c-cb24-11e7-923c-d75d0823140c.png)

This is all that can be done for now pending newly generated log entries that may tell us more.

**Comment by RyanBayne** [comment]
I was too quick to move this to Done. 

We still need to establish why a token already established is not used 1 minute after being received. 

Why does the plugin attempt to get another token? 

Is there an issue with the most recent token being stored?

**Comment by RyanBayne** [comment]
I can confirm that I have already done some work to identify and log any attempt to make an API call that requires a none authorized scope. An attempt will result in a log entry only.

I also need to state that the HTTP 400 or 401 log entries aren't suggesting errors but rather an issue with the way the plugin is configured. That does not rule out a bug causing the plugin to behave as if it isn't configured correctly but after months of use we should have experienced such an issue already.

![image](https://user-images.githubusercontent.com/25900125/33172471-2dd3163c-d048-11e7-8d20-27e1574f3a5c.png)

I would like to see a matrix that is visible to administrators - showing them the status of individual features (services) based on all possible configuration data. With the scopes being the first parameter used to establish this new table.

**Comment by unitedfusionentertainment** [comment]
Since installing the latest update from wordpress, the 401 error has returned https://gyazo.com/f91a887e0ed95e7a37964ca4c4f62943
