### ISSUE TITLE
Improve Shortcode Outputs Sorting Order

### ISSUE THREAD

**Issue by RyanBayne** [RyanBayne/TwitchPress#177]
When the channel status and embed everything shortcodes are used on the same page. The content will appear in reverse order when the status shortcode is first. 

Look at the div for each and improve the layout.

**Comment by andsim** [comment]
take a look at as it is 
https://www.andsim.org/?page_id=10

**Comment by RyanBayne** [comment]
The layout certainly isn't correct but I need to know more technical details especially because the output I get is very different. On my sites the content is contained within the post content area. 


![image](https://user-images.githubusercontent.com/25900125/34075167-4d8c90f4-e2b6-11e7-976f-3e9eb8d12765.png)

In this case it would be telling us where you placed the shortcode. Is it in a post or pages or widgets content? 

Cheers Andsim

**Comment by andsim** [comment]
here picture
![andsim-codeis](https://user-images.githubusercontent.com/831158/34084468-2fabc228-e34f-11e7-9e3a-60417671f83d.png)

**Comment by andsim** [comment]
not look right when i use shortcode

**Comment by andsim** [comment]
i made a big beeboo to my main website, is delete the database

**Comment by RyanBayne** [comment]
The cause who failed to return the shortcode content and instead it was being echoed. 

Andsim confirmed that it displays properly now.
