### ISSUE TITLE
Uncaught Error: Call to undefined method TWITCHPRESS_Twitch_API::get_user_scopes()

### ISSUE THREAD

**Issue by tr1cksnl** [RyanBayne/TwitchPress#284]
PHP Fatal error:  Uncaught Error: Call to undefined method TWITCHPRESS_Twitch_API::get_user_scopes() in /var/www/htdocs/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php:559

**Comment by RyanBayne** [comment]
Line 559 does not contain get_user_scopes() in the latest release. 

In case there is a version mismatch I released version 1.4.0 as I did not have information on the version being used. I assumed it was downloaded from WordPress.org though. 

Thanks for the report.
