### ISSUE TITLE
Long Logging Reported

### ISSUE THREAD

**Issue by RyanBayne** [RyanBayne/TwitchPress#310]
It has been reported that login via Twitch.tv using TwitchPress Login Extension can hang. 

I have little more than that at this time and need users to provide evidence.

**Comment by charlieblossom** [comment]
I'm experiencing issues as well. This is the error I'm encountering with my website.

Catchable fatal error: Argument 1 passed to TWITCHPRESS_Twitch_API_Calls::getUserObject_Authd() must be an instance of string, string given, called in /home/silentsentry/public_html/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php on line 760 and defined in /home/silentsentry/public_html/wp-content/plugins/channel-solution-for-twitch/includes/libraries/twitch/kraken/class.twitch-api-calls.php on line 103

**Comment by RyanBayne** [comment]
Yes, that is a strange one because it states a string is required and a string is giving!

Just about to release an update that should sort your specific issue @charlieblossom but this is not closure on this issue until someone confirms the login no longer takes a long time. 

Thanks for reporting.
