### ISSUE TITLE
Settings > Other API - Deepbot incorrectly labelled as Steam

### ISSUE THREAD

**Issue by ardalista** [RyanBayne/TwitchPress#345]
Noted while looking at the list of services under Other API tab that label 'Steam' is displayed twice.

When clicking on them, one is for Steam and the other is actually for Deepbot.

![image](https://user-images.githubusercontent.com/3156122/81267373-79243200-909a-11ea-8f46-083abcfd5ba6.png)

**Comment by RyanBayne** [comment]
Changed that good work thanks.

![image](https://user-images.githubusercontent.com/25900125/81335932-4c731900-90a0-11ea-9def-121f171426f8.png)
