### ISSUE TITLE
Perks link yields "Invalid post type."

### ISSUE THREAD

**Issue by moertel** [RyanBayne/TwitchPress#346]
I just installed TwitchPress and went through the setup process using the wizard. Logins via Twitch are working fine and content can be gated (so I assume setup was successful). All links in the sidebar menu ("Channels", "Giveaways", etc.) are working but "Perks" is not. `wp-admin/edit.php?post_type=perks` gets loaded and displays `Invalid post type.`

Wordpress: 5.4.1
TwitchPress: 3.4.0
No TwitchPress extensions installed.

Any guidance would be greatly appreciated. If you need more info, let me know!

**Comment by RyanBayne** [comment]
It's actually not a ready feature and I know it's causing some confusion so I'll take action right now. Some of the foundational work is released early to force test it right now especially something that integrations closely with the WP core like a custom-post.

**Comment by moertel** [comment]
Ha, thank you. Glad I didn't mess up my installation. 😅
