### ISSUE TITLE
Twitch avatar too big in user overview

### ISSUE THREAD

**Issue by moertel** [RyanBayne/TwitchPress#347]
For new accounts created in Wordpress by users logging in via the Twitch login button, their avatars appear to be giant:

<img width="732" alt="Screenshot 2020-05-12 at 22 06 56" src="https://user-images.githubusercontent.com/1823966/81740577-78760c00-949d-11ea-9f88-ca9db35d4c64.png">

I'm not actually sure this is a TwitchPress issue but would appreciate if you had a look. Other accounts created via e.g. my Patreon login button work flawlessly and avatars look normal.

Wordpress 5.4.1
Twitchpress 3.4.0

**Comment by RyanBayne** [comment]
Strange I would have thought the image size is restricted by CSS but I'm going to take a quick look now.

**Comment by RyanBayne** [comment]
So there was a filter that seemed like it's meant to display the Twitch logo properly. Didn't bother trying to fix that. I replaced the entire approach instead. 

The new procedure creates a new attachment (media) using the Twitch logo and then uses it to change the user's avatar. Not tested it yet but this can be closed considering a more in-depth approach has been implemented.

**Comment by RyanBayne** [comment]
I initially replaced the old avatar method with a more in-depth approach then closed this.

I suddenly realized the benefit in having both approaches at hand while each are tested and can possibly be an option. So the work is mostly done. Needs testing now.

**Comment by RyanBayne** [comment]
Can finally confirm this problem using Helix so I'll be able to test fixes.

![image](https://user-images.githubusercontent.com/25900125/82098262-84133e00-96fc-11ea-9d58-15c82b2e2763.png)

**Comment by RyanBayne** [comment]
This has been improved. 

![image](https://user-images.githubusercontent.com/25900125/82219016-a2538680-9914-11ea-9dbf-cb8c5ead1aeb.png)
