### ISSUE TITLE
Uncaught Error: Call to undefined method TWITCHPRESS_Twitch_API::get_users_follows()

### ISSUE THREAD

**Issue by moertel** [RyanBayne/TwitchPress#348]
Wordpress 5.4.1
Twitchpress 3.4.0

When logging into Wordpress with Patreon, an exception is thrown:
```
[14-May-2020 19:48:43 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method TWITCHPRESS_Twitch_API::get_users_follows() in /var/www/html/wp-content/plugins/twitchpress/includes/classes/class.twitchpress-sync.php:494
Stack trace:
#0 /var/www/html/wp-content/plugins/twitchpress/includes/classes/class.twitchpress-sync.php(296): TwitchPress_Systematic_Syncing->user_follower_sync('3')
#1 /var/www/html/wp-content/plugins/twitchpress/includes/classes/class.twitchpress-sync.php(237): TwitchPress_Systematic_Syncing->sync_user('3', false, false)
#2 /var/www/html/wp-includes/class-wp-hook.php(287): TwitchPress_Systematic_Syncing->sync_user_on_login('patreon_3185457...', Object(WP_User))
#3 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('patreon_3185457...', Array)
#4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/html/wp-content/plugins/patreon-connect/classes/patreon_login.php(195): do_action('wp_login', 'patreon_3185457...', Object(WP_User))
#6 /var/www/html/wp-content/plugins/patreon-connect/ in /var/www/html/wp-content/plugins/twitchpress/includes/classes/class.twitchpress-sync.php on line 494
```

On the frontend side, a user sees this:
<img width="786" alt="Screenshot 2020-05-14 at 21 49 21" src="https://user-images.githubusercontent.com/1823966/81979401-367bd000-962d-11ea-9570-7881f8389964.png">

Settings for Twitch login should allow Patreon logins (and others) to work:
<img width="847" alt="Screenshot 2020-05-14 at 21 54 35" src="https://user-images.githubusercontent.com/1823966/81979613-8c507800-962d-11ea-9925-a92714863da2.png">

**Comment by RyanBayne** [comment]
Bedtime for me but a quick look at this and the first possible cause is that Kraken is being used instead of Helix. This can be changed in the developer menu on the WP admin toolbar. 

Shouldn't be in Kraken though so that would surprise me. 

get_users_follows() also exists as a method. 

If your using Helix then I may need to run tests with an environment closer to yours - starting with the Patreon plugin.

**Comment by RyanBayne** [comment]
This issue is my top priority and I'll be running tests today to duplicate the problem. 

If I cannot duplicate it I will continue working on my current tasks but continue to monitor this matter closely.

**Comment by moertel** [comment]
Yep, on Kraken. Hm. Which bad things do await me if I switch to Helix? It's a production site, so I wouldn't want any instability there. Your message in the settings is quite clear:

<img width="743" alt="Screenshot 2020-05-15 at 16 18 54" src="https://user-images.githubusercontent.com/1823966/82060521-d128ed00-96c7-11ea-8f90-709c7dc542e3.png">

**Comment by RyanBayne** [comment]
Ignore all that and switch. Your installation will not be affected and you can switch between them. 

If you encounter an issue I'll be right on it. I found a login issue today when on Helix and already working on a fix. I'll update those notices which I've totally forgotten about as I never go there.

**Comment by RyanBayne** [comment]
Closing this on the basis that Kraken is not fully supported.
