### ISSUE TITLE
View Latest Publication Tool breaks Admin Dashboard

### ISSUE THREAD

**Issue by kelsilynstar** [RyanBayne/TwitchPress#358]
As seen in the screenshot below. I can't see what it's actually pulling nor can I do anything else navigation-wise without first going to a new page in the admin tools.

![image](https://user-images.githubusercontent.com/38847941/85324986-daf8f980-b498-11ea-85ba-a9ed6af10532.png)

**Comment by RyanBayne** [comment]
Will take a look at this right now.

The original purpose of the tool was to view the latest post shared to
Twitch.tv when that was possible.
Technically the tool should have been removed but I'll see what I can do
about making it useful.

Thanks

**Comment by RyanBayne** [comment]
I improved the tool and this is what the output now appears...

![image](https://user-images.githubusercontent.com/25900125/85344255-0b678480-b4e7-11ea-96b6-e6390bfcb2d3.png)

Thanks for the feedback.
