### ISSUE TITLE
Sub-Only Content tags not working

### ISSUE THREAD

**Issue by shapingthesilence** [RyanBayne/TwitchPress#362]
I tried adding this tag to my page and ended up crashing it and getting this error.
`[twitchpress_shortcodes shortcode="sub_only-content"]Some subscriber only content goes here.[/twitchpress_shortcodes]`
![Screen Shot 2020-09-05 at 10 42 06 AM](https://user-images.githubusercontent.com/5516101/92307456-b3c4ab00-ef64-11ea-86d2-a07f32e63bd6.png)

**Comment by shapingthesilence** [comment]
Had to deactivate the twitchpress plugin temporarily in order to edit the page and remove the offending shortcode.

**Comment by RyanBayne** [comment]
The shortcode was incorrect in documentation...

[twitchpress_shortcodes shortcode="sub_only-content"]

was meant to be...

[twitchpress_shortcodes shortcode="sub_only_content"]

This was updated in the documentation and I apologise for the confusion.
