### ISSUE TITLE
Follower/Subscription status not syncing to user profile.

### ISSUE THREAD

**Issue by shapingthesilence** [RyanBayne/TwitchPress#363]
I had a viewer who is subscribed to me try logging in to my site using twitchpress and he was unable to view any of the follower only/subscriber only content. His status was not synced to the ultimate member roles I specified in twitchpress nor did they show up under the edit user page.
![Screen Shot 2020-09-09 at 2 55 19 PM](https://user-images.githubusercontent.com/5516101/92641305-87829480-f2ac-11ea-9221-e59c3f14913f.png)

**Comment by RyanBayne** [comment]
A recent release may not solve this issue but it does improve connectivity between WP and Twitch.tv so it should be easier to resolve this matter going forward. 

There are two test tools for obtaining subscription data. Those should be tried first to ensure calls are being made and data returned using the app credentials and subscription-related methods.

**Comment by RyanBayne** [comment]
![image](https://user-images.githubusercontent.com/25900125/107594147-266b3e00-6c09-11eb-91df-ca996061fc1a.png)

**Comment by RyanBayne** [comment]
Subscription features are still high priority but while I await on the community testing changes I will be working on other features. 

@shapingthesilence was great on Discord when it came to troubleshooting but from January onwards I found a couple of bugs that were very difficult to realize and they led to me taking a new approach with subscription syncing. Rendering this issue closed. 

The changes still aren't well tested at this time though and so the plugins ability to offer subscriber related features is still poorer than it was a year ago. I'm waiting for the opportunity to test a channel that offers subscriptions but this requires access to someones site and might take time.
